package animo.realcom.mahakubera.util;

public class ExceptionMessageConstants {

	public static final String ERROR_COMMON_MSG_ERCM000001 = "ERROR-COMMON-MSG_ER001001";

	public static final String LOGIN_ACOUNT_INVALID = "ERROR-LOGIN-INVALID_ER000001";
	public static final String LOGIN_ACOUNT_LOCKED = "ERROR-LOGIN-ACOUNT-LOCKED_ER000002";

	public static final String VENDOR_NOT_FOUND = "ERROR-VENDOR-NOT-FOUND_ER002001";
	public static final String VENDOR_ACOUNT_LOCKED = "ERROR-VENDOR-ACOUNT-LOCKED_ER002002";
	
	public static final String GAME_JODI_PLAY_STATUS_NOT_FOUND = "ERROR-GAME-JODI-PLAY-STATUS-NOT-FOUND";
	public static final String GAME_JODI_TICKET_NOT_FOUND = "ERROR-GAME-JODI-TICKET-NOT-FOUND_ER002002";
	public static final String GAME_JODI_TICKET_TRANSACTION_NOT_FOUND = "ERROR-GAME-JODI-TICKET-TRANSACTION-NOT-FOUND_ER002003";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID = "ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID_ER002004";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID_GAME_COMPLETED="ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID-GAME-COMPLETED_ER002005";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID_GAME_CANCELED="ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID-GAME-CANCELED_ER0020006";
}
