package animo.realcom.mahakubera.util;

public class ExceptionMessageConstants {

	public static final String ERROR_COMMON_MSG_ERCM000001 = "ERROR-COMMON-MSG_ER001001";

	public static final String LOGIN_ACOUNT_INVALID = "ERROR-LOGIN-INVALID_ER000001";
	public static final String LOGIN_ACOUNT_LOCKED = "ERROR-LOGIN-ACOUNT-LOCKED_ER000002";

	public static final String VENDOR_NOT_FOUND = "ERROR-VENDOR-NOT-FOUND_ER002001";
	public static final String VENDOR_ACOUNT_LOCKED = "ERROR-VENDOR-ACOUNT-LOCKED_ER002002";
	
	public static final String GAME_JODI_PLAY_STATUS_NOT_FOUND = "ERROR-GAME-JODI-PLAY-STATUS-NOT-FOUND";
	public static final String GAME_JODI_TICKET_NOT_FOUND = "ERROR-GAME-JODI-TICKET-NOT-FOUND_ER002002";
	public static final String GAME_JODI_TICKET_TRANSACTION_NOT_FOUND = "ERROR-GAME-JODI-TICKET-TRANSACTION-NOT-FOUND_ER002003";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID = "ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID_ER002004";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID_GAME_COMPLETED="ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID-GAME-COMPLETED_ER002005";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID_GAME_CANCELED="ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID-GAME-CANCELED_ER0020006";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID_CANCEL_NOT_ALLOWED="ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID-CANCEL-NOT-ALLOWED_ER002007";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID_CLAIM_NOT_ALLOWED="ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID-CLAIM-NOT-ALLOWED_ER002008";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID_WIN_STATIS_HOLD_OR_LOOSE_NOT_ALLOWED_CLAIM="ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID-WIN-STATIS-HOLD-OR-LOOSE-NOT-ALLOWED-CLAIM_ER002009";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID_CLAIM_NOT_ALLOWED_ON_CANCEL_TRANSACTION="ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID-CLAIM-NOT-ALLOWED-ON-CANCEL-TRANSACTION_ER002010";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID_CANCEL_NOT_ALLOWED_ON_GAME_COMPLETED="ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID-CANCEL-NOT-ALLOWED-ON-GAME-COMPLETED_ER002011";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID_CANCEL_NOT_ALLOWED_ON_GAME_CANCELED="ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID-CANCEL-NOT-ALLOWED-ON-GAME-CANCELED_ER002012";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID_CLAIM_NOT_ALLOWED_ON_GAME_NOT_COMPLETED="ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID-CLAIM-NOT-ALLOWED-ON-GAME-NOT-COMPLETED_ER002013";
	public static final String GAME_JODI_TICKET_TRANSACTION_INVALID_CLAIM_NOT_ALLOWED_ON_GAME_CANCELED="ERROR-GAME-JODI-TICKET-TRANSACTION-INVALID-CLAIM-NOT-ALLOWED-ON-GAME-CANCELED_ER002014";
	
}
